version: "3.3"
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    command: --max_allowed_packet=128M
    ports:
      - 23306:3306
    networks:
      - db
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data/mysql:/var/lib/mysql

  api:
    image: linnhtun/go-gin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - db
      - api
    environment:
      # Password for root access
      GIN_MODE: "debug"
      GO111MODULE: "on"
      IPGEO_APIKEY: "ea1ab2d33c2748d1b304ab8ffc77cfec"
    volumes:
      - ../api:/app
    working_dir: /app
    command: ["sh", "run.sh"]

  front:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - api
    volumes:
      - ../front/.conf:/etc/nginx/conf.d/
      - ../front/build:/usr/share/nginx/html

networks:
  db:
  api:
