version: "3.3"
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    command: --max_allowed_packet=128M
    ports:
      - 23306:3306
    networks:
      - db
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data/mysql:/var/lib/mysql

  api:
    image: linnhtun/go-gin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - db
      - api
    environment:
      # Password for root access
      GIN_MODE: "debug"
      GO111MODULE: "on"
    volumes:
      - ../api:/app
    working_dir: /app
    command: ["sh", "run.sh"]

networks:
  db:
  api:
